runtime: custom
env: flex
service: lazycache

env_variables:
  LAZYCACHE_IMAGESTORE: google
  LAZYCACHE_IMAGESTORE_BUCKET: camhd-app-dev.appspot.com/imagestore

skip_files:
  - main.go

resources:
  cpu: 1
  memory_gb: 3.5

health_check:
  enable_health_check: False

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 4
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5
